# NUMPY

In [67]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
arr.ndim


1

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr.shape

(4,)

In [8]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
arr1.dtype


dtype('int32')

In [12]:
arr1.shape

(2, 4)

In [13]:
arr1.ndim

2

## Zero, One & Empty

In [22]:
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
one = np.ones((3,3), dtype = bool)
one

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [30]:
one = np.ones((3,3), dtype = int)
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
zero = np.zeros((3,3), dtype = str)
zero

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [42]:
empty = np.empty((3,3), dtype = int)
empty

array([[        0,         1,         0],
       [757935405,       684,         0],
       [      768,       544, 757935405]])

# Numpy Function


## Arange()

In [45]:
arg = np.arange(1,13)
arg

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## linspace()

In [50]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

## Reshape()

In [58]:
_3d = arg.reshape(4,3) #cross product hona chiay
_3d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# ravel()

In [59]:
_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [66]:
_3d.flatten('C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [70]:
_3d.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])